Django_notice/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('notice/', include('notice.urls')),
    path('admin/', admin.site.urls),
]

notice/urls.py
from django.urls import path

from . import views

app_name = 'notice'
urlpatterns = [
    # ex: /notice/
    path('', views.IndexView.as_view(), name='index'),
    path('insert/', views.InsertView.as_view(), name='insert'),
    path('imocheck/', views.imo_check, name='imoCheck'),
    path('insert/createVessel/', views.create_vessel, name='createVessel'),
    path('delete/', views.delete_vessel, name='deleteVessel'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:vessel_id>/update', views.update_vessel, name='update'),
]

notice/models.py
from django.db import models

class ShipInfo(models.Model):
    ship_name = models.CharField(max_length=50)
    ship_IMO = models.CharField(max_length=7)
    ship_description = models.CharField(max_length=500)
    ship_status = models.CharField(max_length=1, default=0)
    pub_date = models.DateTimeField('date published')

notice/views.py
import json
import requests
from bs4 import BeautifulSoup
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.utils import timezone
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.db.models import Case, Value, When

from .models import ShipInfo

from django.db.models import Case, When, Value, CharField


class IndexView(generic.ListView):
    template_name = 'notice/index.html'
    context_object_name = 'vessel_list'

    def get_queryset(self):
        queryset = ShipInfo.objects.annotate(
            ship_status_display=Case(
                When(ship_status=1, then=Value('완료')),
                When(ship_status=0, then=Value('실패')),
                output_field=CharField(),
            )
        ).filter(pub_date__lte=timezone.now()).order_by('pub_date')

        return queryset


class DetailView(generic.DetailView):
    model = ShipInfo
    template_name = 'notice/detail.html'
    context_object_name = 'vessel_detail'


class InsertView(generic.TemplateView):
    template_name = 'notice/insert.html'


def create_vessel(request):
    body = json.loads(request.body)
    new_vessel = ShipInfo()
    new_vessel.ship_name = body['name']
    new_vessel.ship_IMO = body['imoNumber']
    new_vessel.ship_description = body['description']
    new_vessel.ship_status = body['status']
    new_vessel.pub_date = timezone.now()
    new_vessel.save()
    return render(request, 'notice/index.html')


def delete_vessel(request):
    body = json.loads(request.body)
    instance = ShipInfo.objects.filter(id=body['id'])
    instance.delete()
    return render(request, 'notice/index.html')


def update_vessel(request, vessel_id):
    vessel_detail = get_object_or_404(ShipInfo, pk=vessel_id)
    vessel_detail.ship_name = request.POST['vesselName']
    vessel_detail.ship_IMO = request.POST['imoNumber']
    vessel_detail.ship_description = request.POST['description']
    vessel_detail.ship_status = request.POST['status']
    vessel_detail.save()
    return HttpResponseRedirect(reverse('notice:index'))


def imo_check(request):
    body = json.loads(request.body)
    imo_num = body['data']
    url = f'https://www.vesselfinder.com/vessels/details/{imo_num}'
    headers = {'User-Agent': 'Mozilla/5.0'}
    response = requests.get(url=url, headers=headers)
    context = {
        'result': response.status_code,
    }
    return JsonResponse(context)

notice/templates/notice/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="https://getbootstrap.com/docs/5.3/assets/css/docs.css"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"></script>
    <title>Vessel Management example</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="/notice">Vessel Management</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarTogglerDemo02"
          aria-controls="navbarTogglerDemo02"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/notice"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <script src="{% static 'notice/js/common.js' %}"></script>
  </body>
</html>

notice/templates/notice/detail.html
{% extends "base.html" %}
  {% load static %}
  {% block content %}
  <div class="bg-body-tertiary p-5 rounded">
    <h1 class="h1">Insert Vessel</h1>
    <form id="updateForm" action="{% url 'notice:update' vessel_detail.id %}" class="needs-validation" method="post" novalidate>
      {% csrf_token %}
      <div class="row g-3">
        <div class="col-sm-6">
          <label for="vesselName" class="form-label">Vessel name</label>
          <input
            type="text"
            class="form-control"
            id="vesselName"
            name="vesselName"
            placeholder=""
            value="{{ vessel_detail.ship_name }}"
            required
          />
          <div class="invalid-feedback">Valid name is required.</div>
        </div>
      </div>
      <div class="row g-3">
        <div class="col-sm-6">
          <label for="imoNumber" class="form-label">IMO number</label>
          <input
            type="number"
            class="form-control"
            id="imoNumber"
            name="imoNumber"
            placeholder=""
            value="{{ vessel_detail.ship_IMO }}"
            required
          />
          <div class="invalid-feedback">Valid IMO number is required.</div>
        </div>
      </div>
      <div class="row g-3">
        <div class="col-sm-6">
          <label for="description" class="form-label">Description</label>
          <input
            type="text"
            class="form-control"
            id="description"
            name="description"
            placeholder=""
            value="{{ vessel_detail.ship_description }}"
          />
        </div>
      </div>
      <div class="row g-3">
        <div class="col-sm-5">
          <label for="status" class="form-label">Status</label>
          <select class="form-select" id="status" name="status" required>
            <option value="0" {% if vessel_detail.ship_status == 0 %} selected {% endif %}>Fail</option>
            <option value="1" {% if vessel_detail.ship_status == 1 %} selected {% endif %}>Success</option>
          </select>
          <div class="invalid-feedback">Please select a valid check Status.</div>
        </div>
      </div>
      <div class="row g-3">
        <div class="col-sm-5" style="margin-top: 30px">
          <button
            id="imoCheckBtn"
            class="btn btn-primary d-inline-flex align-items-center"
            type="button"
          >
            Check IMO number
          </button>
        </div>
      </div>
      <div class="row g-3">
        <div class="col-sm-5" style="margin-top: 30px">
          <button
            class="btn btn-primary align-items-center"
            type="submit"
          >
            Update vessel
          </button>
        </div>
      </div>
      <input id="checkImoYn" type="hidden" value="N" />
    </form>
  </div>
  <script src="{% static 'notice/js/detail.js' %}"></script>
  {% endblock %}

notice/templates/notice/index.html
{% extends "base.html" %}
  {% load static %}
  {% block content %}
    <div class="bg-body-tertiary p-5 rounded">
      <h1 class="h1">Vessel List</h1>
      <table id="vessel-list" class="table table-striped table-sm">
        <caption>A vessel list</caption>
        <thead>
          <th scope="col">Id</th>
          <th scope="col">Vessel Name</th>
          <th scope="col">IMO Number</th>
          <th scope="col">Description</th>
          <th scope="col">Status</th>
          <th scope="col">Pub Date</th>
          <th scope="col">Actions</th>
        </thead>
        <tbody>
        {% if vessel_list %}
          {% for vessels in vessel_list %}
            <tr>
              <td><a href="{% url 'notice:detail' vessels.id %}">{{ vessels.id }}</a></td>
              <td>{{ vessels.ship_name }}</td>
              <td>{{ vessels.ship_IMO }}</td>
              <td>{{ vessels.ship_description }}</td>
              <td>{{ vessels.ship_status_display }}</td>
              <td>{{ vessels.pub_date|date:"Y-m-d" }}</td>
              <td><button class="delete-btn" data-id="{{ vessels.id }}">삭제</button></td>
            </tr>
          {% endfor %}
        {% else %}
            <tr>
                <td colspan="7">No Vessels are available.</td>
            <tr>
        {% endif %}
        </tbody>
      </table>
      <button
        class="btn btn-primary d-inline-flex align-items-center"
        type="button"
        onClick="location.href='/notice/insert/'"
      >
        Add Vessel
      </button>
    </div>
    <script src="{% static 'notice/js/delete.js' %}"></script>
  {% endblock %}

notice/templates/notice/insert.html
{% extends 'base.html' %}
  {% load static %}
  {% block content %}
    <div class="bg-body-tertiary p-5 rounded">
      <h1 class="h1">Insert Vessel</h1>
      <form class="needs-validation" method="post" novalidate>
        <div class="row g-3">
          <div class="col-sm-6">
            <label for="vesselName" class="form-label">Vessel name</label>
            <input
              type="text"
              class="form-control"
              id="vesselName"
              placeholder=""
              value=""
              required
            />
            <div class="invalid-feedback">Valid name is required.</div>
          </div>
        </div>
        <div class="row g-3">
          <div class="col-sm-6">
            <label for="imoNumber" class="form-label">IMO number</label>
            <input
              type="number"
              class="form-control"
              id="imoNumber"
              placeholder=""
              value=""
              required
            />
            <div class="invalid-feedback">Valid IMO number is required.</div>
          </div>
        </div>
        <div class="row g-3">
          <div class="col-sm-6">
            <label for="description" class="form-label">Description</label>
            <input
              type="text"
              class="form-control"
              id="description"
              placeholder=""
              value=""
            />
          </div>
        </div>
        <div class="row g-3">
          <div class="col-sm-5">
            <label for="status" class="form-label">Status</label>
            <select class="form-select" id="status" required>
              <option value="0">Fail</option>
              <option value="1">Success</option>
            </select>
            <div class="invalid-feedback">Please select a valid check Status.</div>
          </div>
        </div>
        <div class="row g-3">
          <div class="col-sm-5" style="margin-top: 30px">
            <button
              id="imoCheckBtn"
              class="btn btn-primary d-inline-flex align-items-center"
              type="button"
            >
              Check IMO number
            </button>
          </div>
        </div>
        <div class="row g-3">
          <div class="col-sm-5" style="margin-top: 30px">
            <button
              id="addVesselBtn"
              class="btn btn-primary align-items-center"
              type="button"
            >
              Add vessel
            </button>
          </div>
        </div>
        <input id="checkImoYn" type="hidden" value="N" />
      </form>
    </div>
    <script src="{% static 'notice/js/insert.js' %}"></script>
  {% endblock %}